language: node_js
node_js:  stable

notifications:
   slack: myspecialway:3s58KKj8R7El4OKWC1xtnZbK

services:
  - docker

before_install:
  - docker pull node:carbon

script:
 - yarn build
 - yarn docker