language: node_js
node_js:  stable

notifications:
   slack: myspecialway:3s58KKj8R7El4OKWC1xtnZbK

services:
  - docker

before_install:
  - docker pull node:carbon
  - lerna bootstrap

script:
 - yarn build
 - yarn docker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - yarn deploy